substitutions:
  name: sonoff-s31
  friendly_name: Sonoff S31
  sensor_throttle: 60s

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.9.0

esp8266:
  early_pin_init: false

# Remove the following line if you're not using Home Assistant or your switch will restart every now and again.
api:
    
ota:
  - platform: esphome
    id: ota_esphome

# Disable UART logging
logger:
  level: INFO
  baud_rate: 0 # (UART logging interferes with cse7766)

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - name: "Button"
    platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay 
  - name: "Connection status"
    platform: status

sensor:
  - name: "Wi-Fi signal"
    platform: wifi_signal
    update_interval: 60s
    disabled_by_default: True
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 2
      disabled_by_default: True
      filters:
        - throttle_average: ${sensor_throttle}
    voltage:
      name: "Voltage"
      accuracy_decimals: 2
      disabled_by_default: True
      filters:
        - throttle_average: ${sensor_throttle}
    power:
      name: "Power"
      id: power
      accuracy_decimals: 2
      filters:
        - throttle_average: ${sensor_throttle}
  - name: "Energy"
    platform: total_daily_energy
    power_id: power

time: # Required for total_daily_energy
  - id: the_time
    platform: sntp

switch:
  - name: ${friendly_name}
    id: relay
    platform: gpio
    pin: GPIO12
    restore_mode: ALWAYS_OFF # Powering the relay may cause damage or instability when the programmer is supplying Vcc.

status_led:
  pin:
    number: GPIO13
    inverted: True